#!/bin/bash -x

set -euo pipefail
IFS=$'\n\t'

rm -rf /tmp/App-af

cpanm -n Dist::Zilla


git clone --depth 2 https://github.com/plicease/App-af.git /tmp/App-af
cd /tmp/App-af
dzil authordeps --missing | cpanm -n
dzil listdeps   --missing | cpanm -n
dzil install --install-command 'cpanm -n .'
